### ISSUE TITLE
Update YML parser to integrate additionnal flags on column

### ISSUE THREAD

**Issue by jeckel** [jeckel/sql-documentor#1]
### Context

Add the possibility to add some flags to columns

### To Do

In the yaml file, add flags
```yml
columns:
  id:
    comment: "Some comment about the PK"
    flags:
      - Primary
      - Unique
      - Deprecated
```
In the generated Markdown file, this flags should be added in the `Attributes` column.
